### ISSUE TITLE
Mapping Kubernetes Resources: Identifying relationships between all standard and custom resources

### ISSUE THREAD

**Issue by leecalcote** [cncf/tag-network#35]
### Description
The OpenAPI specifications for Kubernetes provides taxonomy, but augmenting a graph data model with formalized ontologies enables any number of capabilities, one of the more straightforward is the inferencing requisite for natural language processing, and consequently, a human-centric query / response interaction becomes becomes possible. More importantly, more advanced systems can be built when a graph data model of connected systems is upgraded to be a knowledge semantic graph.
### Objectives
  - YAML-formatted definition of one or more relationships per Kubernetes resource.
  - Documentation of each relationship - per component.
  - Development of new types of genealogies - new types of ways in which resources relate to one another and how these relationships might be visualized.
  - Verification of functional relationships
### Contributor Resources
- Recommended Skills: DevOps, Kubernetes Administration, Light familiarity with all of the CNCF projects and a desire to study each project and their operators/resources.

**Comment by prakrit55** [comment]
Hey @leecalcote, greatly interested in the project for LFX mentorship term mar-may. I would like to know more about it.

**Comment by ChrisJon02** [comment]
hey @leecalcote, this issue is interesting. I'd like to work on this for LFX mentorship

**Comment by alwinsDen** [comment]
Hi @leecalcote   

The channel for Tag-network is not publicly accessible. 

Please do look into it.  

Regards Alwin.

**Comment by nitishmalang** [comment]
hey @leecalcote can you describe more about it. Seems interesting I would like to work on this project in lfx mentorship

**Comment by pandeyshubham03** [comment]
Hey @leecalcote, I'm interested to work on this project for LFX Mentorship. I am a Certified Kubernetes Administrator and I want to enhance my skills with this project. I would like to know more about it. Also, is there any slack link for the same?

**Comment by Nihit25** [comment]
Hey @leecalcote this issue seems really interesting, I would really like to work on this and I'll try my best to contribute

**Comment by leecalcote** [comment]
@Nihit25 @Eeshu-Yadav @pandeyshubham03 @nitishmalang @ChrisJon02 @prakrit55,  contributors of the project have amassed here - https://slack.meshery.io. Join the ongoing conversations there, so that we can support your ramping up on the project, please.
