### ISSUE TITLE
Technical Content Creation: CNCF Challenges 

### ISSUE THREAD

**Issue by leecalcote** [cncf/tag-network#40]
#### Technical Content Creation: CNCF Challenges 

Description: On a periodic basis, the CNCF would like to present a public challenge to those that are interested in participating (e.g. “Challenge: Distributed Tracing with Jaeger”). 

Your mission in this internship is technical content creation of said challenges through use of markdown, Meshery, and any number of other CNCF projects. Challenges will be created using the Meshery Playground and potentially published in the proposed CNCF Hub. They will be similar too, but slightly different from these [example tutorials](https://docs.meshery.io/guides/tutorials/).

Understand that your challenges will be promoted through CNCF channels, reviewed by various project maintainers, and that each challenger (participant) will receive a certain number of points, depending upon whether or not they successfully complete the challenges that you create and in what timeframe they complete those challenges (the faster, the more points). Your challenges will need to vary in level of difficulty. 

**Expected Outcome:** 
  - 10+ new challenges published in CNCF Hub (and Meshery Catalog and Artifact Hub).
  - Challenges can contain more than one objective. Points are earned for each objective completed.
  - Bonus: Extend one or more of Meshery’s Learning Paths.
	
- Recommended Skills: written English, Kubernetes, DevOps, and familiarity with any number of other CNCF projects, like Prometheus, CoreDNS, Istio, Jaeger, Helm, Harbor, OPA, Rook, SPIFEE, Flux, Argo, Flux, Falco, etc., Jekyll, strong organizational skills
- Mentor(s): Lee Calcote (@leecalcote, leecalcote@gmail.com), Nic Jackson (@nicholasjackson, jackson.nic@gmail.com)

**Comment by MeenuyD** [comment]
Hello @leecalcote,
I am very interested in contributing to the CNCF Challenges project. I have experience writing technical content, as evidenced by my blogs on hashcode [https://hashnode.com/@meenuyD]. However, I would appreciate it if you could provide more information about this internship opportunity. Specifically, I would like to understand the expectations and responsibilities involved in creating technical challenges using markdown, Meshery, and other CNCF projects.

**Comment by Mona3087** [comment]
I am interested in this as well.

**Comment by Nihit25** [comment]
Hello @leecalcote, this project seems really interesting and fascinating to me. I'm quite familiar with many CNCF projects like Prometheus, CoreDNS, Jaeger, Harbor, Argo, Flux.  I will make every effort to gain an in-depth understanding of the CNCF projects, like Prometheus, CoreDNS, Istio, Jaeger, Helm, Harbor, OPA, Rook, SPIFEE, Flux, Argo, Flux, Falco, etc., in the coming days.
 
I have decent experience writing content on various topics. I have submitted my application and I really look forward to contributing to this project as much as poosible.

Thank you,
Nihit
