### ISSUE TITLE
TAG Documentation Update: TAG  Network

### ISSUE THREAD

**Issue by riaankleinhans** [cncf/tag-network#42]
This issue supports updating the TAG README, Charter and moving documents to the TAG’s Gdrive. The work will be tracked in the TOC Tracking issue [#1366](https://github.com/cncf/toc/issues/1366).

The following points should be addressed:
- PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
- PR removing TAG repo charter
- PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/tree/main/tags/tag-charters)
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
- Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

**Comment by riaankleinhans** [comment]
Created a [PR](https://github.com/cncf/landscape/pull/3957) to add TAG Network identifiers in the landscape.yml file to the projects listed on the TAG Network README. 
This would allow of updating the README according to the [temple](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md), omitting listed projects and adding a filtered[ TAG Network landscape link](https://landscape.cncf.io/?group=projects-and-products&view-mode=grid&tag=network&project=cncf).

**Comment by rohitsrma** [comment]
Hello @riaankleinhans, I would like to work on this issue. Would it be alright if I address one point at a time and create a PR for each? For example, the first step could be to arrange the README file according to the template.

**Comment by riaankleinhans** [comment]
> Hello @riaankleinhans, I would like to work on this issue. Would it be alright if I address one point at a time and create a PR for each? For example, the first step could be to arrange the README file according to the template.

Thank you @rohitsrma for the offer. This issue is spread over a few repos and I already have it as a work in progress locally. Should push PRs before the end of this week.

**Comment by riaankleinhans** [comment]
> > Hello @riaankleinhans, I would like to work on this issue. Would it be alright if I address one point at a time and create a PR for each? For example, the first step could be to arrange the README file according to the template.
> 
> Thank you @rohitsrma for the offer. This issue is spread over a few repos and I already have it as a work in progress locally. Should push PRs before the end of this week.

@rohitsrma I could guide you on addressing this issue if you are still open to it.
The work in the TOC repo is created in [#1395](https://github.com/cncf/toc/pull/1395)

### What remain to be done here is:
- Update the README according to the template
- You could also refer to the competed README update linked [here](https://github.com/cncf/toc/issues/1366)

 @nicholasjackson @ZackButcher @leecalcote for comment here as well

**Comment by rohitsrma** [comment]
Hello @riaankleinhans, I would love to work on this, but it looks like there is already a PR up.

**Comment by riaankleinhans** [comment]
> Hello @riaankleinhans, I would love to work on this, but it looks like there is already a PR up.

Yes, This PR is done. But there is more work to be done over [here](https://github.com/cncf/toc/issues/1366)
Look at the context, review all the PRs already created, review the templates.
Would be great if you want to pick up on of the other TAG's updates.

**Comment by rohitsrma** [comment]
> > Hello @riaankleinhans, I would love to work on this, but it looks like there is already a PR up.
> 
> Yes, This PR is done. But there is more work to be done over [here](https://github.com/cncf/toc/issues/1366)
> Look at the context, review all the PRs already created, review the templates.
> Would be great if you want to pick up one of the other TAG's updates.
> 

Thank you! I'll go through these.
