### ISSUE TITLE
[assessment] Kuma for inclusion at Sandbox 

### ISSUE THREAD

**Issue by amye** [cncf/tag-network#5]
TOC PR: https://github.com/cncf/toc/pull/437 
TOC Issue with more details: https://github.com/cncf/toc/issues/436 

Link to Presentation: (to be scheduled) https://docs.google.com/presentation/d/1zbeFCR2JBuQWH0XIfYmGpoFerv2fg8Wr7ncHSso860A/edit#slide=id.p 

Github: https://github.com/Kong/kuma

@amye opening this issue to track SIG-Network presentation comments + assessment, see full TOC issue for details.

**Comment by caniszczyk** [comment]
@amye did this happen yet?

**Comment by amye** [comment]
@leecalcote - ok to put this on May 21st's agenda, per discussion in May 7th meeting?

**Comment by nickolaev** [comment]
At the CNCF SIG Network call on May 21st, @subnetmarco did present Kuma.
[Meeting agenda](https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#heading=h.vmi3gay3yroa)
[Video recording](https://www.youtube.com/watch?v=uzD6Kc188xI)
